// refmanifest.js — GENERATED by the photo-harvest scripts; edit those, not this.
//
// Bundled reference photos (all from Wikipedia/Wikimedia Commons, individually
// vetted by eye) with the attribution data their licenses require. Bundling
// means instant + offline for built-in species; custom species still use the
// runtime Wikipedia fetch in refphoto.js.

export const SPECIES_PHOTOS = {
  'african-violet': { file: 'img/species/african-violet.jpg', title: 'Streptocarpus sect. Saintpaulia', pageUrl: 'https://en.wikipedia.org/wiki/Streptocarpus_sect._Saintpaulia', artist: 'RobertoMM', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0' },
  'aloe-vera': { file: 'img/species/aloe-vera.jpg', title: 'Aloe vera', pageUrl: 'https://commons.wikimedia.org/wiki/File:Aloe_vera_in_pot.jpg', artist: 'Mokkie', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0' },
  'anthurium': { file: 'img/species/anthurium.jpg', title: 'Anthurium andraeanum', pageUrl: 'https://en.wikipedia.org/wiki/Anthurium_andraeanum', artist: 'Taken by Fanghong', license: 'CC BY 2.5', licenseUrl: 'https://creativecommons.org/licenses/by/2.5' },
  'begonia': { file: 'img/species/begonia.jpg', title: 'Begonia (wax begonia)', pageUrl: 'https://en.wikipedia.org/wiki/Begonia_cucullata', artist: 'Zythème', license: 'CC0', licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en' },
  'cactus': { file: 'img/species/cactus.jpg', title: 'Cactus', pageUrl: 'https://commons.wikimedia.org/wiki/File:Barbed_cactus_in_flowerpot_with_flowers.jpg', artist: 'Paolo Neo', license: 'Public domain', licenseUrl: '' },
  'calathea': { file: 'img/species/calathea.jpg', title: 'Calathea orbifolia', pageUrl: 'https://commons.wikimedia.org/wiki/File:Houseplant_Calathea_orbifolia.jpg', artist: 'Supsoph', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  'chinese-evergreen': { file: 'img/species/chinese-evergreen.jpg', title: 'Aglaonema', pageUrl: 'https://en.wikipedia.org/wiki/Aglaonema', artist: 'Kurt Stüber [1]', license: 'CC BY-SA 3.0', licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/' },
  'dracaena': { file: 'img/species/dracaena.jpg', title: 'Dracaena marginata', pageUrl: 'https://commons.wikimedia.org/wiki/File:Dracaena_Marginata.jpg', artist: 'Aldrina A Manashe', license: 'CC0', licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en' },
  'english-ivy': { file: 'img/species/english-ivy.jpg', title: 'Hedera helix', pageUrl: 'https://en.wikipedia.org/wiki/Hedera_helix', artist: 'kallerna', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  'fern-boston': { file: 'img/species/fern-boston.png', title: 'Nephrolepis exaltata', pageUrl: 'https://en.wikipedia.org/wiki/Nephrolepis_exaltata', artist: 'Homer Edward Price', license: 'CC BY 2.0', licenseUrl: 'https://creativecommons.org/licenses/by/2.0' },
  'fiddle-leaf-fig': { file: 'img/species/fiddle-leaf-fig.jpg', title: 'Ficus lyrata', pageUrl: 'https://commons.wikimedia.org/wiki/File:Ficus_lyrata_98162192.jpg', artist: 'Diogo Luiz', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  'herb-basil': { file: 'img/species/herb-basil.jpg', title: 'Basil', pageUrl: 'https://en.wikipedia.org/wiki/Basil', artist: 'Photo by David J. Stang', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  'herb-generic': { file: 'img/species/herb-generic.jpg', title: 'Herb', pageUrl: 'https://en.wikipedia.org/wiki/Herb', artist: 'Lauren 240', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  'jade-plant': { file: 'img/species/jade-plant.jpg', title: 'Crassula ovata', pageUrl: 'https://en.wikipedia.org/wiki/Crassula_ovata', artist: 'author is sannse.', license: 'CC BY-SA 3.0', licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/' },
  'monstera': { file: 'img/species/monstera.jpg', title: 'Monstera deliciosa', pageUrl: 'https://en.wikipedia.org/wiki/Monstera_deliciosa', artist: '', license: 'CC BY-SA 3.0', licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/' },
  'orchid-phalaenopsis': { file: 'img/species/orchid-phalaenopsis.jpg', title: 'Phalaenopsis (moth orchid)', pageUrl: 'https://commons.wikimedia.org/wiki/File:Orchid%C3%A9e_Phalaenopsis_blanche_en_pot_suspendu_04.jpg', artist: 'Tohinde', license: 'CC0', licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en' },
  'peace-lily': { file: 'img/species/peace-lily.jpg', title: 'Spathiphyllum', pageUrl: 'https://en.wikipedia.org/wiki/Spathiphyllum', artist: 'JJ Harrison (https://www.jjharrison.com.au/)', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0' },
  'philodendron': { file: 'img/species/philodendron.jpg', title: 'Philodendron hederaceum', pageUrl: 'https://en.wikipedia.org/wiki/Philodendron_hederaceum', artist: 'KENPEI', license: 'CC BY-SA 3.0', licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/' },
  'pothos': { file: 'img/species/pothos.jpg', title: 'Epipremnum aureum', pageUrl: 'https://en.wikipedia.org/wiki/Epipremnum_aureum', artist: 'Mokkie', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0' },
  'rubber-plant': { file: 'img/species/rubber-plant.jpg', title: 'Ficus elastica', pageUrl: 'https://en.wikipedia.org/wiki/Ficus_elastica', artist: 'B.navez', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0' },
  'snake-plant': { file: 'img/species/snake-plant.jpg', title: 'Dracaena trifasciata', pageUrl: 'https://en.wikipedia.org/wiki/Dracaena_trifasciata', artist: 'Mokkie', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0' },
  'spider-plant': { file: 'img/species/spider-plant.jpg', title: 'Chlorophytum comosum', pageUrl: 'https://en.wikipedia.org/wiki/Chlorophytum_comosum', artist: 'Hierbabuena_0611.JPG: Dtarazona derivative work: Peter coxhead (talk)', license: 'Public domain', licenseUrl: '' },
  'string-of-pearls': { file: 'img/species/string-of-pearls.jpg', title: 'Curio rowleyanus', pageUrl: 'https://en.wikipedia.org/wiki/Curio_rowleyanus', artist: 'Flickr user Forest and Kim Starr', license: 'CC BY 2.0', licenseUrl: 'https://creativecommons.org/licenses/by/2.0' },
  'succulent-generic': { file: 'img/species/succulent-generic.jpg', title: 'Echeveria (succulent)', pageUrl: 'https://en.wikipedia.org/wiki/Echeveria', artist: 'Eria Wei', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  'tropical-generic': { file: 'img/species/tropical-generic.jpg', title: 'Dieffenbachia (tropical foliage)', pageUrl: 'https://en.wikipedia.org/wiki/Dieffenbachia', artist: 'Krzysztof Ziarnek, Kenraiz', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  'zz-plant': { file: 'img/species/zz-plant.jpg', title: 'Zamioculcas', pageUrl: 'https://en.wikipedia.org/wiki/Zamioculcas', artist: 'User:WeFt', license: 'CC BY-SA 3.0', licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/' },
};

export const SYMPTOM_PHOTOS = {
  'yellow-leaves': { file: 'img/symptoms/yellow-leaves.jpg', pageUrl: 'https://commons.wikimedia.org/wiki/File:Sweetgum-leaf-interveinal-chlorosis.jpg', artist: 'Jim Conrad', license: 'Public domain', licenseUrl: '',
    caption: { en: 'Real example: interveinal chlorosis — the leaf pales while the veins stay green (a classic hungry-plant sign).', nl: 'Echt voorbeeld: chlorose — het blad verbleekt terwijl de nerven groen blijven (klassiek teken van voedingstekort).' } },
  'pests': { file: 'img/symptoms/pests.jpg', pageUrl: 'https://commons.wikimedia.org/wiki/File:Tetranychus_urticae_with_silk_threads.jpg', artist: 'Gilles San Martin', license: 'CC BY-SA 2.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    caption: { en: 'Real example: a spider mite up close with its silk — to the naked eye just a moving speck and fine webbing.', nl: 'Echt voorbeeld: een spintmijt van dichtbij met haar spinsel — met het blote oog niet meer dan een bewegend stipje en fijn webwerk.' } },
};
